config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :tweets do
    end
    resources :likes
  end
  
  get '/tweets/retweet/:id', to: 'tweets#retweet', as: 'retweet'

  devise_for :users
  
  resources :users do
    resources :friends
  end

  get '/:hashtag', to: 'tweets#hashtag_search', as: 'hashtag'

  get '/api/news', to: 'api#index'
  get "/api/:date1/:date2", to: 'api#between_dates'
  post '/api/create', to: 'api#create'
  

  root to: 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :retweets, class_name: "Tweet", foreign_key: "tweet_id", dependent: :destroy
    belongs_to :parent_tweet, class_name: "Tweet", optional: true

    validates :content, presence: true

    def get_user_name
        self.user.name
    end

    def get_user_photo
        self.user.photo_url
    end

    def get_like_photo
        self.likes.user_id.photo_url
    end

    def self.tweets_for_me(x)
        @my_friends = Friend.where(user_id: x.id)
        friend_id_array = []
        @my_friends.each do |my_friend|
            friend_id_array << my_friend.friend_id
        end
        self.where(user_id: friend_id_array).or(self.where(user_id: x.id))
    end
    
    def self.search_my_tweets(x)
        @my_tweets = Tweet.all
        my_tweet_id_array = []
        @my_tweets.each do |my_tweet|
            if my_tweet.content.include? "#{x}"
                my_tweet_id_array << my_tweet.id
            end
        end
        self.where(id: my_tweet_id_array)
    end

    def as_json(*args)
        {
            :id => self.id,
            :content => self.content,
            :user_id => self.user_id,
            :like_count => self.likes.count,
            :retweets_count => self.retweets.count,
            :retwitted_from => self.tweet_id,
        }
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /tweets or /tweets.json
  def index
    @tweet = Tweet.new
    @@retweet = 0

    if user_signed_in?
      @users = User.add_friends(current_user)
    end
    
    if params[:tweetsearch].present?
      @tweets = Tweet.search_my_tweets(params[:tweetsearch]).page(params[:page]).order("created_at DESC")
    elsif params[:hashtag].present?
      @tweets = Tweet.search_my_tweets("##{params[:hashtag]}").page(params[:page]).order("created_at DESC")
      @users = User.add_friends(current_user)
    elsif user_signed_in?
      @tweets = Tweet.tweets_for_me(current_user).page(params[:page]).order("created_at DESC")
      @users = User.add_friends(current_user)
    else
      @tweets = Tweet.all.page(params[:page]).order("created_at DESC")
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    if user_signed_in?
      @tweet = Tweet.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.tweet_id = @@retweet
    

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Has creado un tweet!" }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def retweet
    @tweet = Tweet.new
    @@retweet = params[:id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :tweet_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<div class="container">
  <%= form_with(model: tweet) do |form| %>
    <% if tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>


    <div class="card text-center mx-auto col-md-6 mb-3">
      <h3 class="card-title py-3">Crear nuevo tweet</h3>
      <div class="form-group">
          <%= form.text_area(:content, rows: 3, class: 'col-md-7') %>
      </div>
      <div class="actions my-2">
        <%= form.submit "Crear nuevo tweet", :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

app/views/tweets/_formretweet.html.erb
<%= form_with(model: tweet) do |form| %>
    <div class="card text-center" style="width: 45rem">
        <h5 class="card-title pt-2">Crear nuevo tweet</h5>
        <div class="form-group">
            <%= form.text_area(:content, cols: 50, rows: 5) %>
        </div>
        <div class="actions my-2">
            <%= form.submit "Crear nuevo tweet", :class => 'btn btn-primary' %>
        </div>
    </div>
    <% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
    <!-- Verificamos que el usuario este logeado para poder crear tweets y seguir amigos -->
    <% if user_signed_in? %>

    <div class="container">
        <p id="notice"><%= notice %></p>
        <h1>Tweets</h1>
        <!-- Modal para agregar amigos -->
        <button type="button" class="btn btn-primary d-inline-block" data-toggle="modal" data-target="#exampleModal">Agregar amigos</button>

        <!-- Modal con los amigos -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <h3 class="modal-title mb-3" id="exampleModalLabel">Amigos para agregar</h5>
                        <!--listado de usuarios-->
                        <% @users.each do |user|%>
                            <!-- evitamos que usuario pueda seguirse a sí mismo -->
                            <% if user.id == current_user.id %>
                            <% else %>
                                <div class="card mx-auto mb-3" style="width: 60%">
                                    <div class="card-body text-center">
                                        <img src="<%= user.photo_url %>" width="60" height="60" class="rounded-circle mb-2">
                                        <div class="d-inline-block">
                                            <h4 class="card-title pl-3"><%= user.name %></h4>
                                        </div>
                                        <p>Tweets <%= user.tweets.count %></p>
                                        <%= link_to(user_friends_path(user.id), method: :post)do%><i class="fas fa-user-plus fa-2x"></i><% end %>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <%= render 'form', tweet: @tweet %>
<% end %>

<div class="mx-1">
    <%= render 'shared/tweetslist', tweet: @tweet %>
</div>


<br>

<!-- paginamos los tweets -->
<div class="container mx-auto">
    <div class="col-md-8 offset-md-3 mb-4">
        <%= link_to_next_page @tweets, 'Mostrar más tweets' %>
        <br>
        <%= link_to_prev_page @tweets, 'Volver a tweets anteriores' %>
    </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/retweet.html.erb
<div class="container">
    <%= render 'formretweet', tweet: @tweet %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <h2>Likes</h2>

  <div class="container">
    <!-- iteramos los likes para traer los id de usuario y luego sus fotos -->
    <p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <div>
      <% Like.where(tweet_id: @tweet.id).each do |photo| %>
        <% photo_url =  photo.user_id %>
          <div class="d-inline-block p-2">
            <img src="<%= User.find(photo_url).photo_url%>" width="60" height="60" class="rounded-circle">
            <p><%= User.find(photo_url).name %></p>
          </div>
      <% end %>
    </div>
  </div>

  <br>

  <%= link_to 'Back', tweets_path %>
</div>