config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
    resources :tweets do
    end
    resources :likes
  end
  
  get '/tweets/retweet/:id', to: 'tweets#retweet', as: 'retweet'

  devise_for :users
  
  resources :users do
    resources :friends
  end

  get '/:hashtag', to: 'tweets#hashtag_search', as: 'hashtag'

  get '/api/news', to: 'api#index'
  get "/api/:date1/:date2", to: 'api#between_dates'
  post '/api/create', to: 'api#create'
  

  root to: 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_likesmodal.html.erb
<h2>Likes</h2>

<div class="container">
    <!-- iteramos los likes para traer los id de usuario y luego sus fotos -->
    <p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <div>
        <% Like.where(tweet_id: @tweet.id).each do |photo| %>
        <% photo_url =  photo.user_id %>
            <img src="<%= User.find(photo_url).photo_url%>" width="60" height="60" class="rounded-circle">
            <p><%= User.find(photo_url).name %></p>
        <% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #1DA1F2">
    <div class="my-auto mx-4">
        <a class="navbar-brand text-white" href="<%= root_path %>">Inicio</a>
    </div>
    <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li><%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary mx-4'  %></li>
        <% else %>
            <li><%= button_to 'Ingresar', new_user_session_path, :class => 'btn btn-primary mx-4' %></li>
            <li><%= button_to 'Registrarse', new_user_registration_path, method: :get, :class => 'btn btn-primary mx-4' %></li>
        <% end %>
    </ul>
        <form class="form-inline">
        <div class="d-inline-block">
            <input class="form-control" type="search" placeholder="Buscar" aria-label="Buscar" name="tweetsearch">
        </div>
        <div class="d-inline-block">
            <button class="btn btn-outline-light" type="submit">Buscar</button>
        </div>
    </form>
</nav>

app/views/shared/_tweetslist.html.erb
<!-- iteramos cada tweet para que se desplieguen en nuestro index -->
<% @tweets.each do |tweet| %>
    <div class="card mt-1 mb-4 col-md-6 mx-auto">
        <div class="col-md-12">
            <div class="card-body">
                <h4 class="card-title"><%= tweet.get_user_name %></h5>
                <img src="<%= tweet.get_user_photo %>" width="60" height="60" class="rounded-circle">
                <div class="d-inline-block p-4">
                    <p>
                        <% my_content_array = tweet.content.split%>
                        <% my_content_array.each do |element| %>
                            <% if element.start_with?("#") %>
                                <% element.slice!(0) %>
                                <a href="?hashtag=<%= element %>">#<%= element %></a>
                            <% else %>
                                <%= element %>
                            <% end %>
                        <% end %>
                    </p>
                </div>
                <!-- solo el propio usuario puede editar y borrar su tweet -->
                <% if user_signed_in? %>
                    <% if tweet.user_id == current_user.id %>
                        <%= link_to 'Edit', edit_tweet_path(tweet) %></td>
                        <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                <% end %>
                <!-- agregamos vista retweet-->
                <% if tweet.tweet_id %>
                    <% if tweet.tweet_id > 0 %>
                        <div class="card p-2 mb-3">
                            <% retweet_id = tweet.tweet_id %>
                            <% retweet = Tweet.find(retweet_id) %>
                            <div class="card-body p-0">   
                                <h4><%= retweet.get_user_name %></h4>
                                <img src="<%= retweet.get_user_photo %>" width="60" height="60" class="rounded-circle">
                                <div class="d-inline-block p-4">
                                    <p>
                                        <% my_content_array = retweet.content.split%>
                                        <% my_content_array.each do |element| %>
                                            <% if element.start_with?("#") %>
                                                <% element.slice!(0) %>
                                                <a href="?hashtag=<%= element %>">#<%= element %></a>
                                            <% else %>
                                                <%= element %>
                                            <% end %>
                                        <% end %>
                                    </p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
                <!-- modal para mostrar likes -->
                <div class="d-block">
                    <%= link_to "Created #{time_ago_in_words(tweet.created_at)} ago", tweet %>  
                </div>

                <div class="d-inline-block ml-2 col-md-4" style="width:100">
                <p>
                    <!-- mostramos cantidad de likes -->
                    <%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%>
                    <!-- mostramos cantidad de retweets -->
                    <%= tweet.retweets.count %> <%= (tweet.retweets.count) == 1 ? 'Retweet' : 'Retweets'%>
                </p>
                </div>

                <div class="col-md-6 d-inline-block">
                    <div class="row">
                        <div class="col-md-7">
                        </div>
                        <div class="col-3">
                            <!-- verificamos que el usuario haya hecho like -->
                            <% if user_signed_in? %>
                                <% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
                                <!-- si ya hizo like, mostramos boton unlike, sino, boton like -->
                                <% if pre_like %>
                                    <%= link_to(tweet_like_path(tweet.id, pre_like), method: :delete) do %><i class="fas fa-thumbs-up fa-2x d-inline-block"></i><% end %>
                                <% else %>
                                    <%= link_to(tweet_likes_path(tweet.id), method: :post)do%><i class="far fa-thumbs-up fa-2x d-inline-block"></i><% end %>
                                <% end %>
                            </div>
                            <div class="d-inline-block col-2">
                                <!-- habilitamos boton de retweet -->
                                <%= button_to 'Retweet', retweet_path(tweet.id), method: :get, :class => 'btn btn-primary' %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
<% end %>